### ISSUE TITLE
DNS resolution & MQTT broker blackout cause Eclipse Paho MQTT client to die with no way to recover

### ISSUE THREAD

**Issue by climategadgets** [home-climate-control/esphome2influxdb#21]
### Trigger Event
DNS server and MQTT broker went down together for hardware upgrade

### Expected Behavior
Non-event, keep going as usual after DNS resolution and MQTT broker are back up

### Actual Behavior
System rendered inoperable, exception happened within Eclipse Paho internal thread with no callback outside

### Exception Trace
```
2024-02-23 20:07:17,008 ERROR MqttReader MQTT Ping: 57bff499-8b93-4eb0-bbc0-2359dc395d3c [] Lost connection
 org.eclipse.paho.client.mqttv3.MqttException: Timed out waiting for a response from the server
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:747) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:818) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:804) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:79) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at java.util.TimerThread.mainLoop(Unknown Source) [?:?]
        at java.util.TimerThread.run(Unknown Source) [?:?]
2024-02-23 20:07:23,141 FATAL MqttReader MQTT Ping: 57bff499-8b93-4eb0-bbc0-2359dc395d3c [] Reconnect failed, giving up
 org.eclipse.paho.client.mqttv3.MqttException: MqttException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.UnknownHostException: <REDACTED>
        at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
        ... 1 more

```

**Comment by climategadgets** [comment]
Invalid as submitted because Eclipse Paho is now gone (#17). Closing, will watch and reopen with updated description if necessary.
